# Mojibake's DB
FROM centos:latest
MAINTAINER Jordan M <jordan@defestri.org>

RUN yum update -y

ADD mariadb.repo /etc/yum.repos.d/mariadb.repo

RUM yum clean all && yum install -y MariaDB-server MariaDB-client


